export const COLLAPSE_MENU = "COLLAPSE_MENU";
export const COLLAPSE_TOGGLE = "COLLAPSE_TOGGLE";
export const FULL_SCREEN = "FULL_SCREEN";
export const FULL_SCREEN_EXIT = "FULL_SCREEN_EXIT";
export const CHANGE_LAYOUT = "CHANGE_LAYOUT";
export const NAV_CONTENT_LEAVE = "NAV_CONTENT_LEAVE";
export const NAV_COLLAPSE_LEAVE = "NAV_COLLAPSE_LEAVE";

export const SUCCESS_LOGIN = "SUCCESS_LOGIN";
export const START_LOGIN = "START_LOGIN";
export const FAILD_LOGIN = "FAILD_LOGIN";

export const SUCCESS_CHECK_AUTH = "SUCCESS_CHECK_AUTH";
export const START_CHECK_AUTH = "START_CHECK_AUTH";
export const FAILD_CHECK_AUTH = "FAILD_CHECK_AUTH";

export const SUCCESS_LOGOUT = "SUCCESS_LOGOUT";

export const SUCCESS_GETLICTYPES = "SUCCESS_GETLICTYPES";
export const START_GETLICTYPES = "START_GETLICTYPES";
export const FAILD_GETLICTYPES = "FAILD_GETLICTYPES";
export const CHANGE_LICENSETYPE = "CHANGE_LICENSETYPE";

export const CHANGE_STATE = "CHANGE_STATE";

export const SUCCESS_GETPROFESSIONS = "SUCCESS_GETPROFESSIONS";
export const START_GETPROFESSIONS = "START_GETPROFESSIONS";
export const FAILD_GETPROFESSIONS = "FAILD_GETPROFESSIONS";
export const CHANGE_PROFESSION = "CHANGE_PROFESSION";

export const CHANGE_OTHERFILTERS = "CHANGE_OTHERFILTERS";
export const CHANGE_COMBO_FILTERS = "CHANGE_COMBO_FILTERS";

export const SUCCESS_QUERY = "SUCCESS_QUERY";
export const START_QUERY = "START_QUERY";
export const FAILD_QUERY = "FAILD_QUERY";

export const SUCCESS_COUNT_QUERY = "SUCCESS_COUNT_QUERY";
export const START_COUNT_QUERY = "START_COUNT_QUERY";
export const FAILD_COUNT_QUERY = "FAILD_COUNT_QUERY";

export const SUCCESS_USER_COLUMN = "SUCCESS_USER_COLUMN";
export const START_USER_COLUMN = "START_USER_COLUMN";
export const FAILD_USER_COLUMN = "FAILD_USER_COLUMN";

export const SUCCESS_GET_REGISTRED_USERS = "SUCCESS_GET_REGISTRED_USERS";
export const START_GET_REGISTRED_USERS = "START_GET_REGISTRED_USERS";
export const FAILD_GET_REGISTRED_USERS = "FAILD_GET_REGISTRED_USERS";

export const SUCCESS_USER_ASIGNED_COLUMNS = "SUCCESS_USER_ASIGNED_COLUMNS";
export const START_USER_ASIGNED_COLUMNS = "START_USER_ASIGNED_COLUMNS";
export const FAILD_USER_ASIGNED_COLUMNS = "FAILD_USER_ASIGNED_COLUMNS";

export const SUCCESS_GET_LAYOUT = "SUCCESS_GET_LAYOUT";
export const START_GET_LAYOUT = "START_GET_LAYOUT";
export const FAILD_GET_LAYOUT = "FAILD_GET_LAYOUT";

export const CHANGE_REG_USER = "CHANGE_REG_USER";

export const CHANGE_USER_ASIGNED_COLUMNS = "CHANGE_USER_ASIGNED_COLUMNS";
export const CHANGE_UNASIGNED_COLUMNS = "CHANGE_UNASIGNED_COLUMNS";

export const SUCCESS_POST_COLUMN = "SUCCESS_POST_COLUMN";
export const START_POST_COLUMN = "START_POST_COLUMN";
export const FAILD_POST_COLUMN = "FAILD_POST_COLUMN";

export const SUCCESS_POST_USER_LIC_TYPES = "SUCCESS_POST_USER_LIC_TYPES";
export const START_POST_USER_LIC_TYPES = "START_POST_USER_LIC_TYPES";
export const FAILD_POST_USER_LIC_TYPES = "FAILD_POST_USER_LIC_TYPES";

export const CHANGE_USER_LIC_TYPE = "CHANGE_USER_LIC_TYPE";

export const SUCCESS_GET_USER_LIC_TYPES = "SUCCESS_GET_USER_LIC_TYPES";
export const START_GET_USER_LIC_TYPES = "START_GET_USER_LIC_TYPES";
export const FAILD_GET_USER_LIC_TYPES = "FAILD_GET_USER_LIC_TYPES";

export const SUCCESS_GET_PROFESSIONS = "SUCCESS_GET_PROFESSIONS";
export const START_GET_PROFESSIONS = "START_GET_PROFESSIONS";
export const FAILD_GET_PROFESSIONS = "FAILD_GET_PROFESSIONS";

export const SUCCESS_GET_USER_PROFESSIONS = "SUCCESS_GET_USER_PROFESSIONS";
export const START_GET_USER_PROFESSIONS = "START_GET_USER_PROFESSIONS";
export const FAILD_GET_USER_PROFESSIONS = "FAILD_GET_USER_PROFESSIONS";

export const CHANGE_USER_ASIGNED_PROFESSIONS =
  "CHANGE_USER_ASIGNED_PROFESSIONS";
export const CHANGE_UNASIGNED_PROFESSIONS = "CHANGE_UNASIGNED_PROFESSIONS";

export const SUCCESS_POST_USER_PROFESSION = "SUCCESS_POST_USER_PROFESSION";
export const START_POST_USER_PROFESSION = "START_POST_USER_PROFESSION";
export const FAILD_POST_USER_PROFESSION = "FAILD_POST_USER_PROFESSION";

export const SUCCESS_POST_REGISTER_USER = "SUCCESS_POST_REGISTER_USER";
export const START_POST_REGISTER_USER = "START_POST_REGISTER_USER";
export const FAILD_POST_REGISTER_USER = "FAILD_POST_REGISTER_USER";
