const statuses = {
  "TOWNHOUSE FOR SALE": false,
  "LOT / LAND FOR SALE": false,
  ACTIVE: false,
  CONTINGENT: false,
  "CONDO FOR SALE": false,
  "HOME FOR SALE": false,
  "FOR SALE": false,
  PENDING: false,
  "HOUSE FOR SALE": false,
  "CONTINGENT - SHOW": false,
  "PENDING INSPECTION": false,
  "CONTRACT PENDING": false,
  "FOR SALE BY OWNER": false,
  "ACCEPTING BACKUPS": false,
  "CONTINGENT OFFER": false,
  "PENDING FEASIBILITY": false,
  "UNDER CONTRACT": false,
  FOR_SALE: false,
  "APARTMENT FOR SALE": false,
  SOLD: false,
  "CO-OP FOR SALE": false,
  "FOR SALE UNDER CONTRACT": false,
  AUCTION: false,
};
